### PR TITLE
Add online media field

### PR DESCRIPTION
**Pull request by SwithFr**
Why limit slideshow to images ? :D

### CODE REVIEW

**Comment by smeeckaert** [comment]
It's missing a migration and your field name has two underscores in it, and you should check if the application novius_onlinemedia_files is installed before trying to use it.

Perhaps instead of creating a new field for each new integration an eav property can be put in place, not sure if it's a good choice but at least it's kinda future proof :cat:

**Comment by Meroje** [comment]
I would rather make it a polymorphic relation

**Comment by smeeckaert** [comment]
Better idea in fact.

**Comment by jguyomard** [comment]
noviusos_slideshow can't require novius_onlinemediafiles : Novius OS Slideshow is an Official Application, contrary to OnlineMediaFiles.
:-1:

**Comment by smeeckaert** [comment]
Word has been spoken, see ya !

**Comment by jguyomard** [comment]
You can create a new app that extends noviusos_slideshow and add your feature.

**Pull request closed without merging**
